name       : c-ares
version    : 1.13.0
release    : 3
source     :
    - https://c-ares.haxx.se/download/c-ares-1.13.0.tar.gz : 03f708f1b14a26ab26c38abd51137640cb444d3ec72380b21b20f1a8d2861da7
license    : MIT
component  : programming
summary    : C library that performs DNS requests and name resolves asynchronously
description: |
    This is c-ares, an asynchronous resolver library. It is intended for applications which need to perform DNS queries without blocking, or need to perform multiple DNS queries in parallel. The primary examples of such applications are servers which communicate with multiple clients and programs with graphical user interfaces.
setup      : |
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    %configure CPPFLAGS='-D_FORTIFY_SOURCE=2' --disable-static
build      : |
    %make
install    : |
    %make_install
