name       : c-ares
version    : 1.15.0
release    : 4
source     :
    - https://c-ares.haxx.se/download/c-ares-1.15.0.tar.gz : 6cdb97871f2930530c97deb7cf5c8fa4be5a0b02c7cea6e7c7667672a39d6852
license    : MIT
component  : programming.library
summary    : C library that performs DNS requests and name resolves asynchronously
description: |
    This is c-ares, an asynchronous resolver library. It is intended for applications which need to perform DNS queries without blocking, or need to perform multiple DNS queries in parallel. The primary examples of such applications are servers which communicate with multiple clients and programs with graphical user interfaces.
setup      : |
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    %configure CPPFLAGS='-D_FORTIFY_SOURCE=2' --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    cd test
    ./configure
    make