name       : c-ares
version    : 1.15.0
release    : 5
source     :
    - https://github.com/c-ares/c-ares/archive/cares-1_15_0.tar.gz : 7deb7872cbd876c29036d5f37e30c4cbc3cc068d59d8b749ef85bb0736649f04
license    : MIT
component  : programming.library
summary    : C library that performs DNS requests and name resolves asynchronously
description: |
    This is c-ares, an asynchronous resolver library. It is intended for applications which need to perform DNS queries without blocking, or need to perform multiple DNS queries in parallel. The primary examples of such applications are servers which communicate with multiple clients and programs with graphical user interfaces.
setup      : |
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    %reconfigure CPPFLAGS='-D_FORTIFY_SOURCE=2' --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    cd test
    ./configure
    make
