name       : c-ares
version    : 1.19.1
release    : 7
source     :
    - https://github.com/c-ares/c-ares/archive/refs/tags/cares-1_19_1.tar.gz : 9eadec0b34015941abdf3eb6aead694c8d96a192a792131186a7e0a86f2ad6d9
license    : MIT
component  : programming.library
summary    : C library that performs DNS requests and name resolves asynchronously
description: |
    This is c-ares, an asynchronous resolver library. It is intended for applications which need to perform DNS queries without blocking, or need to perform multiple DNS queries in parallel. The primary examples of such applications are servers which communicate with multiple clients and programs with graphical user interfaces.
setup      : |
    %patch -p1 < $pkgfiles/Remove-live-tests.patch
    %cmake_ninja -DCARES_BUILD_TESTS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
